/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UpdateInteractionRequest = IDL.Record({
  'interactionType' : IDL.Opt(IDL.Text),
  'materialsShared' : IDL.Opt(IDL.Text),
  'hcpName' : IDL.Opt(IDL.Text),
  'sentiment' : IDL.Opt(IDL.Text),
  'followUp' : IDL.Opt(IDL.Text),
  'outcomes' : IDL.Opt(IDL.Text),
  'samples' : IDL.Opt(IDL.Nat),
  'topics' : IDL.Opt(IDL.Text),
  'datetime' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const InteractionRecord = IDL.Record({
  'id' : IDL.Nat,
  'interactionType' : IDL.Text,
  'materialsShared' : IDL.Text,
  'hcpName' : IDL.Text,
  'createdAt' : Timestamp,
  'sentiment' : IDL.Text,
  'followUp' : IDL.Text,
  'outcomes' : IDL.Text,
  'samples' : IDL.Nat,
  'topics' : IDL.Text,
  'datetime' : IDL.Text,
});
export const AiChatResponse = IDL.Record({
  'tool' : IDL.Text,
  'message' : IDL.Text,
  'structuredData' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'editInteraction' : IDL.Func(
      [IDL.Nat, UpdateInteractionRequest],
      [Result],
      [],
    ),
  'getGroqApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'getHcpNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getInteractionById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(InteractionRecord)],
      ['query'],
    ),
  'getInteractions' : IDL.Func([], [IDL.Vec(InteractionRecord)], ['query']),
  'logInteraction' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'processAiChat' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [AiChatResponse],
      [],
    ),
  'setGroqApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UpdateInteractionRequest = IDL.Record({
    'interactionType' : IDL.Opt(IDL.Text),
    'materialsShared' : IDL.Opt(IDL.Text),
    'hcpName' : IDL.Opt(IDL.Text),
    'sentiment' : IDL.Opt(IDL.Text),
    'followUp' : IDL.Opt(IDL.Text),
    'outcomes' : IDL.Opt(IDL.Text),
    'samples' : IDL.Opt(IDL.Nat),
    'topics' : IDL.Opt(IDL.Text),
    'datetime' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const InteractionRecord = IDL.Record({
    'id' : IDL.Nat,
    'interactionType' : IDL.Text,
    'materialsShared' : IDL.Text,
    'hcpName' : IDL.Text,
    'createdAt' : Timestamp,
    'sentiment' : IDL.Text,
    'followUp' : IDL.Text,
    'outcomes' : IDL.Text,
    'samples' : IDL.Nat,
    'topics' : IDL.Text,
    'datetime' : IDL.Text,
  });
  const AiChatResponse = IDL.Record({
    'tool' : IDL.Text,
    'message' : IDL.Text,
    'structuredData' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'editInteraction' : IDL.Func(
        [IDL.Nat, UpdateInteractionRequest],
        [Result],
        [],
      ),
    'getGroqApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'getHcpNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getInteractionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InteractionRecord)],
        ['query'],
      ),
    'getInteractions' : IDL.Func([], [IDL.Vec(InteractionRecord)], ['query']),
    'logInteraction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'processAiChat' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [AiChatResponse],
        [],
      ),
    'setGroqApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };