/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiChatResponse {
  'tool' : string,
  'message' : string,
  'structuredData' : string,
}
export interface InteractionRecord {
  'id' : bigint,
  'interactionType' : string,
  'materialsShared' : string,
  'hcpName' : string,
  'createdAt' : Timestamp,
  'sentiment' : string,
  'followUp' : string,
  'outcomes' : string,
  'samples' : bigint,
  'topics' : string,
  'datetime' : string,
}
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateInteractionRequest {
  'interactionType' : [] | [string],
  'materialsShared' : [] | [string],
  'hcpName' : [] | [string],
  'sentiment' : [] | [string],
  'followUp' : [] | [string],
  'outcomes' : [] | [string],
  'samples' : [] | [bigint],
  'topics' : [] | [string],
  'datetime' : [] | [string],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'editInteraction' : ActorMethod<[bigint, UpdateInteractionRequest], Result>,
  'getGroqApiKey' : ActorMethod<[], string>,
  'getHcpNames' : ActorMethod<[], Array<string>>,
  'getInteractionById' : ActorMethod<[bigint], [] | [InteractionRecord]>,
  'getInteractions' : ActorMethod<[], Array<InteractionRecord>>,
  'logInteraction' : ActorMethod<
    [string, string, string, string, string, bigint, string, string, string],
    bigint
  >,
  'processAiChat' : ActorMethod<[string, [] | [string]], AiChatResponse>,
  'setGroqApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];