/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface AiChatResponse {
    tool: string;
    message: string;
    structuredData: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UpdateInteractionRequest {
    interactionType?: string;
    materialsShared?: string;
    hcpName?: string;
    sentiment?: string;
    followUp?: string;
    outcomes?: string;
    samples?: bigint;
    topics?: string;
    datetime?: string;
}
export interface InteractionRecord {
    id: bigint;
    interactionType: string;
    materialsShared: string;
    hcpName: string;
    createdAt: Timestamp;
    sentiment: string;
    followUp: string;
    outcomes: string;
    samples: bigint;
    topics: string;
    datetime: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    editInteraction(id: bigint, req: UpdateInteractionRequest): Promise<Result>;
    getGroqApiKey(): Promise<string>;
    getHcpNames(): Promise<Array<string>>;
    getInteractionById(id: bigint): Promise<InteractionRecord | null>;
    getInteractions(): Promise<Array<InteractionRecord>>;
    logInteraction(hcpName: string, interactionType: string, datetime: string, topics: string, materialsShared: string, samples: bigint, sentiment: string, outcomes: string, followUp: string): Promise<bigint>;
    processAiChat(userMessage: string, interactionContext: string | null): Promise<AiChatResponse>;
    setGroqApiKey(key: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { InteractionRecord as _InteractionRecord, Result as _Result, UpdateInteractionRequest as _UpdateInteractionRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async editInteraction(arg0: bigint, arg1: UpdateInteractionRequest): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.editInteraction(arg0, to_candid_UpdateInteractionRequest_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editInteraction(arg0, to_candid_UpdateInteractionRequest_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroqApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroqApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroqApiKey();
            return result;
        }
    }
    async getHcpNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHcpNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHcpNames();
            return result;
        }
    }
    async getInteractionById(arg0: bigint): Promise<InteractionRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractionById(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractionById(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInteractions(): Promise<Array<InteractionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInteractions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInteractions();
            return result;
        }
    }
    async logInteraction(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logInteraction(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logInteraction(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async processAiChat(arg0: string, arg1: string | null): Promise<AiChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.processAiChat(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAiChat(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setGroqApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGroqApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGroqApiKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Result_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InteractionRecord]): InteractionRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_UpdateInteractionRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInteractionRequest): _UpdateInteractionRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interactionType?: string;
    materialsShared?: string;
    hcpName?: string;
    sentiment?: string;
    followUp?: string;
    outcomes?: string;
    samples?: bigint;
    topics?: string;
    datetime?: string;
}): {
    interactionType: [] | [string];
    materialsShared: [] | [string];
    hcpName: [] | [string];
    sentiment: [] | [string];
    followUp: [] | [string];
    outcomes: [] | [string];
    samples: [] | [bigint];
    topics: [] | [string];
    datetime: [] | [string];
} {
    return {
        interactionType: value.interactionType ? candid_some(value.interactionType) : candid_none(),
        materialsShared: value.materialsShared ? candid_some(value.materialsShared) : candid_none(),
        hcpName: value.hcpName ? candid_some(value.hcpName) : candid_none(),
        sentiment: value.sentiment ? candid_some(value.sentiment) : candid_none(),
        followUp: value.followUp ? candid_some(value.followUp) : candid_none(),
        outcomes: value.outcomes ? candid_some(value.outcomes) : candid_none(),
        samples: value.samples ? candid_some(value.samples) : candid_none(),
        topics: value.topics ? candid_some(value.topics) : candid_none(),
        datetime: value.datetime ? candid_some(value.datetime) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
